#steps:
#- name: 'bash'
#  args: ['pwd']
#- name: 'bash'
#  args: ['ls']
steps:
  - name: maven:3-jdk-8
    entrypoint: mvn
    args: ["package","-DskipTests","-f","helloworld/pom.xml"]
#  - name: maven:3-jdk-8
#    entrypoint: mvn
#    args: ["test","-f","helloworld/pom.xml"]
#  - name: maven:3-jdk-8
#    entrypoint: mvn
#    args: ["package", "-Dmaven.test.skip=true","-f","helloworld/pom.xml"]
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "gcr.io/$PROJECT_ID/hellospring", "helloworld/."]
images: ["gcr.io/$PROJECT_ID/hellospring"]
