#steps:
#- name: 'bash'
#  args: ['pwd']
#- name: 'bash'
#  args: ['ls']
steps:
  - name: maven:3-jdk-8
    entrypoint: mvn
    args: ["test","-f","workspace/helloworld/pom.xml"]
#  - name: maven:3-jdk-8
#    entrypoint: mvn
#    args: ["package", "-Dmaven.test.skip=true","-f","helloworld/pom.xml"]
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "gcr.io/$PROJECT_ID/hellospring", "--build-arg=JAR_FILE=target/hello-spring-1.0.0.jar", "."]
images: ["gcr.io/$PROJECT_ID/hellospring"]
